### ISSUE TITLE
Cannot read property settings of undefined, and other errors

### ISSUE THREAD

**Issue by scf4** [tvkhoa/react-tippy#17] opened 2017-08-21 13:49 UTC
I'm getting a lot of these errors from react-tippy in my logs

<img width="456" alt="screen shot 2017-08-21 at 14 43 13" src="https://user-images.githubusercontent.com/768234/29521885-2fb81640-867f-11e7-8339-15bb84c03d61.png">

<img width="841" alt="screen shot 2017-08-21 at 14 43 55" src="https://user-images.githubusercontent.com/768234/29521890-36605ca0-867f-11e7-95d4-fc710da49734.png">

<img width="882" alt="screen shot 2017-08-21 at 14 45 29" src="https://user-images.githubusercontent.com/768234/29521934-6e95e590-867f-11e7-8f6f-3f11a9b20917.png">

And also this one, but less often:

<img width="893" alt="screen shot 2017-08-21 at 14 44 56" src="https://user-images.githubusercontent.com/768234/29521911-5849f178-867f-11e7-81ae-6aa685012a54.png">

Before I go digging in the source, any idea what it might be?

**Comment by mshwery** [comment] 2017-09-08 02:59
I'm encountering the same issue as well. This seems to happen while hovering over a tooltip component that is unmounting.

**Comment by tvkhoa** [comment] 2017-09-10 08:38
@mshwery I fixed the race condition in `1.2.2`, also make it up-to-date with tippy js.

 @scf4 Please update this lib and tell me if your issues are still there.

Thank you 🍡

**Comment by Pustelto** [comment] 2017-09-18 13:00
I have similar issue, event after upgrade to 1.2.2 As mentioned above, seems like a problem with unmounting (maybe listeners not properly removed) .

**Comment by Tsury** [comment] 2017-10-09 11:09
My production users are reporting crashes caused by this... Using 1.2.2.

**Comment by Kerumen** [comment] 2017-10-16 13:31
Same problem here. `1.2.2` as well.

**Comment by woophi** [comment] 2017-10-18 14:09
If you have tippy.js and react-tippy both installed in your projects, it would cause this issue.

**Comment by Tsury** [comment] 2017-10-18 22:52
I just checked and this is not my case...

**Comment by vincentracine** [comment] 2017-10-20 10:06
Receiving the same problem using `1.2.2`

**Comment by ZoharLiran** [comment] 2017-11-12 21:56
Seeing the same issue - only using `react-tippy - 1.2.2`

**Comment by sshadmand** [comment] 2017-11-25 06:25
Seeing the same issue - only using react-tippy - 1.2.2.

I noticed the issue when using tippy with a component on Storybook (https://github.com/storybooks/storybook). It occurs when I have two components using tippy, one with a blank title, the other with text. Going back and forth between Storybook stories gave me the same error a O.P.

**Comment by lmikos-neurosys** [comment] 2017-12-07 10:07
I have the same problem using `react-tippy 1.2.2. `

**Comment by ZoharLiran** [comment] 2017-12-08 00:15
I opened a PR to add guards:
https://github.com/tvkhoa/react-tippy/pull/36

if someone has any words of wisdom or suggestions I'll be more than happy to make further modifications

**Comment by liamm12** [comment] 2018-02-04 08:15
this problem occurs if your package missed some files, So you need to do is to remove your current package then install it through this code `npm install --save react-tippy` then don't forget to import the files 
```
import 'react-tippy/dist/tippy.css';
import { Tooltip,} from 'react-tippy';
```
if you still getting this error try to install tippy.js through this code `npm install --save tippy.js` if it's already installed reinstall it

if you still getting this error you can just delete tippy.js and try again

**Comment by floric** [comment] 2018-02-08 13:27
@liamm12 
Somehow this didn't work for me. I already created a wrapper for all existing places with the title prop like this:

`const {
    children,
    title,
    html,
    ...otherProps
  } = props;

  return (
    <TippyTooltip
      html={title ? <span>{title}</span> : html}
      {...otherProps}
    >
      {props.children}
    </TippyTooltip>`

This should remove title and html from the props and make it always use the html prop. But unfortnately, I still have the error.
I also tried adding tippy.js manually, but this shouldn't have any impact, if I understood the problem correctly.

**Comment by liamm12** [comment] 2018-03-05 14:33
@floric Did you get any problems if you used a simple TippyTooltip like

```
<Tooltip
  title="Helllo"
  position="bottom"
  trigger="click"
>
  <p>
    Click here to show popup
  </p>
</Tooltip>
```
Let me know


When you're using html attribute try to use it into `<p>` like
```
 <Tooltip
          trigger="mouseenter"
          size='small'
          html={(
            <p>{this.state.show 
            ? <span>{this.state.title}</span> 
              : <span>{this.state.titleTwo}</span>}</p>
          )}>
          Hover me
                                    </Tooltip>
      </div>
```

https://codesandbox.io/s/528rw96o4p

**Comment by kpennell** [comment] 2018-03-24 22:48
@Pustelto any luck on this?

**Comment by tvkhoa** [comment] 2019-10-23 00:41
Hi all,
I merge the PR #36 and publish a new build. Just add 1 more check for settings data.
I will close this issue here. Feel free to reopen if it happens again so that we can investigate more

**Closed** 2019-10-23 00:41 UTC
